/*
* generated by Xtext
*/
package snomed.visualization.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VisualizationDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return snomed.visualization.dsl.ui.internal.VisualizationDslActivator.getInstance().getInjector("snomed.visualization.dsl.VisualizationDsl");
	}
	
}
