/*
* generated by Xtext
*/
package snomed.visualization.dsl;

import snomed.visualization.dsl.parser.antlr.VisualizationDslParser;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VisualizationDslStandaloneSetup extends VisualizationDslStandaloneSetupGenerated{

private static VisualizationDslStandaloneSetup instance;
	
	private VisualizationDslParser parser;
	
	public static VisualizationDslStandaloneSetup getInstance() {
		if (null == instance) {
			synchronized (VisualizationDslStandaloneSetup.class) {
				if (null == instance) {
					instance = new VisualizationDslStandaloneSetup();
				}
			}
		}
		
		return instance;
	}

	public static void doSetup() {
		new VisualizationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	public VisualizationDslParser getParser() {
		return parser;
	}
	
	private VisualizationDslStandaloneSetup() {
		parser = createInjectorAndDoEMFRegistration().getInstance(VisualizationDslParser.class);
	}
}

