/*
* generated by Xtext
*/
package snomed.visualization.dsl;

import org.eclipse.xtext.serializer.impl.Serializer;

import snomed.visualization.dsl.parser.antlr.VisualizationDslParser;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
@SuppressWarnings("restriction")
public class VisualizationDslStandaloneSetup extends VisualizationDslStandaloneSetupGenerated{

private static VisualizationDslStandaloneSetup instance;
	
	private VisualizationDslParser parser;
	private Serializer serializer;
	
	public static VisualizationDslStandaloneSetup getInstance() {
		if (null == instance) {
			synchronized (VisualizationDslStandaloneSetup.class) {
				if (null == instance) {
					instance = new VisualizationDslStandaloneSetup();
				}
			}
		}
		
		return instance;
	}

	public static void doSetup() {
		new VisualizationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	public VisualizationDslParser getParser() {
		return parser;
	}
	
	private VisualizationDslStandaloneSetup() {
		parser = createInjectorAndDoEMFRegistration().getInstance(VisualizationDslParser.class);
		serializer = createInjectorAndDoEMFRegistration().getInstance(Serializer.class);
	}

	public Serializer getSerializer() {
		return serializer;
	}
}

