/*
 * generated by Xtext
 */
package snomed.visualization.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VisualizationDslRuntimeModule extends snomed.visualization.dsl.AbstractVisualizationDslRuntimeModule {

}
