/*
* generated by Xtext
*/
package snomed.visualization.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VisualizationDslStandaloneSetup extends VisualizationDslStandaloneSetupGenerated{

	public static void doSetup() {
		new VisualizationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

