/*
 * generated by Xtext
 */
package snomed.visualization.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import snomed.visualization.dsl.ui.internal.VisualizationDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VisualizationDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VisualizationDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VisualizationDslActivator.getInstance().getInjector(VisualizationDslActivator.SNOMED_VISUALIZATION_DSL_VISUALIZATIONDSL);
	}
	
}
