/*
 * generated by Xtext
 */
package snomed.visualization.dsl.ui.contentassist

import snomed.visualization.dsl.ui.contentassist.AbstractVisualizationDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VisualizationDslProposalProvider extends AbstractVisualizationDslProposalProvider {
}
