/*
 * generated by Xtext
 */
package snomed.visualization.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VisualizationDslUiModule extends snomed.visualization.dsl.ui.AbstractVisualizationDslUiModule {
	public VisualizationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
